### ISSUE TITLE
Mark deprecated

### ISSUE THREAD

**Issue by wbt** [amir20/phantomjs-node#898]
Maintenance of the underlying phantomjs library was suspended last year, following [an](https://carstenwindler.de/software-testing/phantomjs-is-discontinued/) [announcement](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE) the year before.  The PhantomJS [official website](https://phantomjs.org/) opens by saying:

>Important: PhantomJS development is suspended until further notice ([more details](https://github.com/ariya/phantomjs/issues/15344)).

Nowhere in the readme (republished on [npm](https://www.npmjs.com/package/phantom)) is this core but outdated dependency mentioned.

The last publish of the library, as noted on the [NPM page](https://www.npmjs.com/package/phantom), was 4 months ago, suggesting more currency than there might really be - it [looks active](https://github.com/amir20/phantomjs-node/commits/master)!  However, there are [several issues](https://github.com/ariya/phantomjs/issues) in PhantomJS's functionality and it's been deprecated. 

**This package should be [marked as deprecated](https://docs.npmjs.com/cli/deprecate) in NPM.**  
Explanatory text should also be added to the readme.  

Doing so will help reduce the number of projects adding this as a dependency and encourage projects already using it to shift to something more maintained, like headless Chrome. 

This would take relatively little time and could help reduce the flow of incoming Issues and associated attention requirements.  @amir20, do you have permissions to do this?

Thanks for all your work while this project was active!

**Comment by amir20** [comment]
I have been thinking about this for a while. Not many issues come in. And since PhantomJs's announcement, I have seen less people using phantom. To me, deprecating means stop using this project. It is not maintained. Bugs won't be fixed and questions won't be answered.  That's not the case. There is a difference with a dependency being deprecated vs the actual project being deprecated. 

I am still responding to bugs, security bugs and questions. That's probably why people still use this project. 

What makes more sense is to highlight in the readme file that one of the decencies has been deprecated.  I have already made it clear that this is just a wrapper around phantomjs. So perhaps I'll make it more clear and add new wording around it's deprecation?

**Comment by amir20** [comment]
I created this https://github.com/amir20/phantomjs-node/pull/899. I am thinking how I would handle this if I had real paying customers. I think it makes sense to completely deprecate this project within some timeframe or below some usage. I was thinking another year or less than 100K/month downloads.

**Comment by amir20** [comment]
Haven’t heard back. So closing.

**Comment by wbt** [comment]
I hadn't realized you were waiting to hear back.  Was there a question above, not self-answered in [#899](https://github.com/amir20/phantomjs-node/pull/899)?

**Comment by amir20** [comment]
I asked a question above. 

> So perhaps I'll make it more clear and add new wording around its deprecation?

But I think it's ok now. I have updated the README with a new note regarding the deprecation of phantomjs and my plan of support going forward.

**Comment by wbt** [comment]
To me, that read like a statement about what you planned to do, which happened to have a question mark at the end even though that didn't make grammatical sense.   Apologies, but I still don't understand what if any question is implied there, or what kinds of answers you expected.

To me, marking something as deprecated provides a signal to users that they should switch off of something and find an alternative (e.g. Puppeteer), not necessarily the end of patches.  If this were my project, I probably would have marked it as deprecated and made the readme change a little clearer that you're planning to keep the *wrapper* maintained a little while longer, while not addressing bugs in the underlying PhantomJS.  

However, this isn't my project, and you've intentionally chosen a course of action which is different but does not seem unreasonable and at this point not uninformed about the deprecation of the underlying library.
